---
version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    links:
      - api
      - admin
    depends_on:
      - api
      - admin
    networks:
      - local
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000
    environment:
      LISTEN_ADDRESS:
      LISTEN_PORT: 3000
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: 12345
      DB_NAME: postgres
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - local
#    volumes:
#      - ./api/node_modules:/app/node_modules:rw
#      - ./api:/app:rw
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - 3000
    environment:
      NODE_ENV: development
    links:
      - api
    depends_on:
      - api
    networks:
      - local
#    volumes:
#      - ./admin/node_modules:/app/node_modules:rw
#      - ./admin:/app:rw
  postgres:
    image: postgres:latest
    ports:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    networks:
      - local
    volumes:
      - postgres-1:/var/lib/postgresql/data

volumes:
  postgres-1:

networks:
  local:
    driver: bridge